// front_end/owui/src/lib/components/common/HarvisMascot.svelte
<script lang="ts">
	// Animated Harvis mascot (blue robot). Ported from
	// newjfrontend/components/mascots/HarvisMascot.tsx — same states and
	// rAF-driven bob/antenna/wave animation, re-hued teal → blue.
	import { onMount, onDestroy } from 'svelte';

	export let state: 'idle' | 'lookLeft' | 'lookRight' | 'wave' | 'talking' | 'angry' = 'idle';
	export let size = 60;
	export let className = '';
	export let interactive = false;

	let currentState: string = state;
	let bobOffset = 0;
	let antennaWiggle = 0;
	let armRotation = 0;
	let clickCount = 0;
	let isAngry = false;
	let isStartled = false;

	let rafId: number | null = null;
	let cycleTimer: ReturnType<typeof setInterval> | null = null;
	let clickTimer: ReturnType<typeof setTimeout> | null = null;
	let angryTimer: ReturnType<typeof setTimeout> | null = null;
	let startleTimer: ReturnType<typeof setTimeout> | null = null;
	let waving = false;
	let waveFrame = 0;

	const CYCLE = ['idle', 'lookLeft', 'idle', 'lookRight', 'idle', 'wave'];

	$: eyeOffset = currentState === 'lookLeft' ? -4 : currentState === 'lookRight' ? 4 : 0;
	$: isSmiling = currentState === 'idle' || currentState === 'wave';

	$: syncState(state, isAngry);

	const syncState = (s: string, angry: boolean) => {
		if (cycleTimer) {
			clearInterval(cycleTimer);
			cycleTimer = null;
		}
		if (angry) {
			currentState = 'angry';
			return;
		}
		if (s !== 'idle') {
			currentState = s;
			return;
		}
		currentState = 'idle';
		let i = 0;
		cycleTimer = setInterval(() => {
			i = (i + 1) % CYCLE.length;
			currentState = CYCLE[i];
		}, 2000);
	};

	$: onCurrentState(currentState);
	const onCurrentState = (cs: string) => {
		if (cs === 'wave') {
			waving = true;
			waveFrame = 0;
		} else {
			waving = false;
			armRotation = 0;
		}
	};

	onMount(() => {
		let frame = 0;
		const loop = () => {
			frame++;
			bobOffset = Math.sin(frame * 0.05) * 2;
			antennaWiggle = Math.sin(frame * 0.08) * 3;
			if (waving) {
				waveFrame++;
				if (waveFrame < 40) {
					armRotation = Math.sin(waveFrame * 0.3) * 30;
				} else {
					armRotation = 0;
					waving = false;
				}
			}
			rafId = requestAnimationFrame(loop);
		};
		rafId = requestAnimationFrame(loop);
	});

	onDestroy(() => {
		if (rafId !== null) cancelAnimationFrame(rafId);
		if (cycleTimer) clearInterval(cycleTimer);
		if (clickTimer) clearTimeout(clickTimer);
		if (angryTimer) clearTimeout(angryTimer);
		if (startleTimer) clearTimeout(startleTimer);
	});

	const handleClick = () => {
		if (!interactive) return;
		clickCount++;
		if (clickCount >= 4) {
			isAngry = true;
			isStartled = false;
			clickCount = 0;
			if (angryTimer) clearTimeout(angryTimer);
			angryTimer = setTimeout(() => {
				isAngry = false;
			}, 1000);
		} else {
			isStartled = true;
			if (startleTimer) clearTimeout(startleTimer);
			startleTimer = setTimeout(() => {
				isStartled = false;
			}, 300);
		}
		if (clickTimer) clearTimeout(clickTimer);
		clickTimer = setTimeout(() => {
			clickCount = 0;
		}, 2000);
	};

	const ACCENT = '#6FA0FF';
	const ANGRY = '#E53E3E';
	$: accent = isAngry ? ANGRY : ACCENT;
</script>

<!-- svelte-ignore a11y-click-events-have-key-events a11y-no-noninteractive-element-interactions -->
<svg
	width={size}
	height={size}
	viewBox="0 0 60 70"
	class="{className} {interactive ? 'cursor-pointer' : ''}"
	style="transform: translateY({bobOffset + (isStartled ? -8 : 0)}px) scale({isStartled
		? 1.1
		: 1}); transition: {isStartled ? 'transform 0.1s ease-out' : 'transform 0.3s ease'}"
	xmlns="http://www.w3.org/2000/svg"
	role="img"
	aria-hidden="true"
	on:click={handleClick}
>
	<defs>
		<filter id="harvisGlow" x="-50%" y="-50%" width="200%" height="200%">
			<feGaussianBlur stdDeviation="1.5" result="coloredBlur" />
			<feMerge>
				<feMergeNode in="coloredBlur" />
				<feMergeNode in="SourceGraphic" />
			</feMerge>
		</filter>
		<linearGradient id="harvisBodyGradient" x1="0%" y1="0%" x2="0%" y2="100%">
			<stop offset="0%" stop-color="#5B8DEF" />
			<stop offset="100%" stop-color="#2F5FD8" />
		</linearGradient>
		<linearGradient id="harvisScreenGradient" x1="0%" y1="0%" x2="0%" y2="100%">
			<stop offset="0%" stop-color="#1A2C5D" />
			<stop offset="100%" stop-color="#0D152A" />
		</linearGradient>
		<linearGradient id="harvisAngryGradient" x1="0%" y1="0%" x2="0%" y2="100%">
			<stop offset="0%" stop-color="#FC8181" />
			<stop offset="100%" stop-color="#E53E3E" />
		</linearGradient>
	</defs>

	<!-- antennae -->
	<g style="transform-origin: 20px 8px; transform: rotate({antennaWiggle}deg)">
		<line x1="20" y1="8" x2="16" y2="0" stroke={accent} stroke-width="2" stroke-linecap="round" />
		<circle cx="16" cy="2" r="3" fill={accent} filter="url(#harvisGlow)" />
	</g>
	<g style="transform-origin: 40px 8px; transform: rotate({-antennaWiggle}deg)">
		<line x1="40" y1="8" x2="44" y2="0" stroke={accent} stroke-width="2" stroke-linecap="round" />
		<circle cx="44" cy="2" r="3" fill={accent} filter="url(#harvisGlow)" />
	</g>

	<!-- head + screen -->
	<rect
		x="12"
		y="8"
		width="36"
		height="30"
		rx="6"
		fill={isAngry ? 'url(#harvisAngryGradient)' : 'url(#harvisBodyGradient)'}
	/>
	<rect x="16" y="12" width="28" height="22" rx="3" fill="url(#harvisScreenGradient)" />

	<!-- eyes -->
	<g style="transform: translateX({eyeOffset}px); transition: transform 0.3s ease">
		{#if isAngry}
			<line x1="19" y1="15" x2="28" y2="18" stroke={ANGRY} stroke-width="2.5" stroke-linecap="round" />
			<line x1="41" y1="15" x2="32" y2="18" stroke={ANGRY} stroke-width="2.5" stroke-linecap="round" />
			<ellipse cx="24" cy="22" rx="4" ry="2" fill={ANGRY} />
			<ellipse cx="24" cy="22" rx="2" ry="1" fill="#FED7D7" />
			<ellipse cx="36" cy="22" rx="4" ry="2" fill={ANGRY} />
			<ellipse cx="36" cy="22" rx="2" ry="1" fill="#FED7D7" />
		{:else if isStartled}
			<circle cx="24" cy="20" r="5" fill={ACCENT} filter="url(#harvisGlow)" />
			<circle cx="24" cy="20" r="2.5" fill="#EAF1FF" />
			<circle cx="24" cy="19" r="1" fill="#ffffff" />
			<circle cx="36" cy="20" r="5" fill={ACCENT} filter="url(#harvisGlow)" />
			<circle cx="36" cy="20" r="2.5" fill="#EAF1FF" />
			<circle cx="36" cy="19" r="1" fill="#ffffff" />
		{:else if isSmiling}
			<path
				d="M21 21 Q24 17 27 21"
				stroke={ACCENT}
				stroke-width="2.5"
				stroke-linecap="round"
				fill="none"
				filter="url(#harvisGlow)"
			/>
			<path
				d="M33 21 Q36 17 39 21"
				stroke={ACCENT}
				stroke-width="2.5"
				stroke-linecap="round"
				fill="none"
				filter="url(#harvisGlow)"
			/>
		{:else}
			<ellipse cx="24" cy="20" rx="3" ry="4" fill={ACCENT} filter="url(#harvisGlow)" />
			<ellipse cx="24" cy="20" rx="1.5" ry="2" fill="#EAF1FF" />
			<ellipse cx="36" cy="20" rx="3" ry="4" fill={ACCENT} filter="url(#harvisGlow)" />
			<ellipse cx="36" cy="20" rx="1.5" ry="2" fill="#EAF1FF" />
		{/if}
	</g>

	<!-- mouth -->
	{#if isAngry}
		<path d="M24 30 Q30 26 36 30" stroke={ANGRY} stroke-width="2" stroke-linecap="round" fill="none" />
	{:else if isSmiling && !isStartled}
		<path
			d="M24 28 Q30 33 36 28"
			stroke={ACCENT}
			stroke-width="2"
			stroke-linecap="round"
			fill="none"
			filter="url(#harvisGlow)"
		/>
	{/if}

	<!-- legs + base -->
	<rect
		x="14"
		y="38"
		width="10"
		height="28"
		rx="3"
		fill={isAngry ? 'url(#harvisAngryGradient)' : 'url(#harvisBodyGradient)'}
	/>
	<rect
		x="36"
		y="38"
		width="10"
		height="28"
		rx="3"
		fill={isAngry ? 'url(#harvisAngryGradient)' : 'url(#harvisBodyGradient)'}
	/>
	<rect
		x="14"
		y="48"
		width="32"
		height="8"
		rx="2"
		fill={isAngry ? 'url(#harvisAngryGradient)' : 'url(#harvisBodyGradient)'}
	/>

	<!-- arms (right one waves) -->
	<rect x="4" y="42" width="6" height="14" rx="3" fill={accent} />
	<g
		style="transform-origin: 53px 42px; transform: rotate({armRotation}deg); transition: {currentState ===
		'wave'
			? 'none'
			: 'transform 0.3s ease'}"
	>
		<rect x="50" y="42" width="6" height="14" rx="3" fill={accent} />
	</g>
</svg>

// front_end/newjfrontend/components/mascots/HarvisMascot.tsx
"use client"

import { useState, useEffect, useCallback } from "react"

type MascotState = "idle" | "lookLeft" | "lookRight" | "wave" | "talking" | "angry"

interface HarvisMascotProps {
  state?: MascotState
  size?: number
  className?: string
  interactive?: boolean
}

export function HarvisMascot({ state = "idle", size = 60, className = "", interactive = false }: HarvisMascotProps) {
  const [currentState, setCurrentState] = useState<MascotState>(state)
  const [eyeOffset, setEyeOffset] = useState(0)
  const [armRotation, setArmRotation] = useState(0)
  const [bobOffset, setBobOffset] = useState(0)
  const [antennaWiggle, setAntennaWiggle] = useState(0)
  const [clickCount, setClickCount] = useState(0)
  const [isAngry, setIsAngry] = useState(false)
  const [isStartled, setIsStartled] = useState(false)
  const [clickTimer, setClickTimer] = useState<NodeJS.Timeout | null>(null)

  const handleClick = useCallback(() => {
    if (!interactive) return

    setClickCount(prev => {
      const newCount = prev + 1
      if (newCount >= 4) {
        setIsAngry(true)
        setIsStartled(false)
        setTimeout(() => {
          setIsAngry(false)
          setClickCount(0)
        }, 1000)
        return 0
      } else {
        setIsStartled(true)
        setTimeout(() => setIsStartled(false), 300)
      }
      return newCount
    })

    if (clickTimer) clearTimeout(clickTimer)
    const timer = setTimeout(() => setClickCount(0), 2000)
    setClickTimer(timer)
  }, [interactive, clickTimer])

  useEffect(() => {
    return () => {
      if (clickTimer) clearTimeout(clickTimer)
    }
  }, [clickTimer])

  useEffect(() => {
    if (isAngry) {
      setCurrentState("angry")
      return
    }

    if (state !== "idle") {
      setCurrentState(state)
      return
    }

    const sequence = ["idle", "lookLeft", "idle", "lookRight", "idle", "wave"] as MascotState[]
    let index = 0

    const interval = setInterval(() => {
      index = (index + 1) % sequence.length
      setCurrentState(sequence[index])
    }, 2000)

    return () => clearInterval(interval)
  }, [state, isAngry])

  useEffect(() => {
    switch (currentState) {
      case "lookLeft":
        setEyeOffset(-4)
        break
      case "lookRight":
        setEyeOffset(4)
        break
      default:
        setEyeOffset(0)
    }
  }, [currentState])

  useEffect(() => {
    if (currentState !== "wave") {
      setArmRotation(0)
      return
    }

    let frame = 0
    const animate = () => {
      frame++
      setArmRotation(Math.sin(frame * 0.3) * 30)
      if (frame < 40) {
        requestAnimationFrame(animate)
      } else {
        setArmRotation(0)
      }
    }
    animate()
  }, [currentState])

  useEffect(() => {
    let frame = 0
    let animationId: number
    const animate = () => {
      frame++
      setBobOffset(Math.sin(frame * 0.05) * 2)
      setAntennaWiggle(Math.sin(frame * 0.08) * 3)
      animationId = requestAnimationFrame(animate)
    }
    animationId = requestAnimationFrame(animate)
    return () => cancelAnimationFrame(animationId)
  }, [])

  const isLooking = currentState === "lookLeft" || currentState === "lookRight"
  const isSmiling = currentState === "idle" || currentState === "wave"

  const jumpOffset = isStartled ? -8 : 0
  const startleScale = isStartled ? 1.1 : 1

  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 60 70"
      className={`${className} ${interactive ? "cursor-pointer" : ""}`}
      style={{ 
        transform: `translateY(${bobOffset + jumpOffset}px) scale(${startleScale})`,
        transition: isStartled ? "transform 0.1s ease-out" : "transform 0.3s ease"
      }}
      onClick={handleClick}
    >
      <defs>
        <filter id="harvisGlow" x="-50%" y="-50%" width="200%" height="200%">
          <feGaussianBlur stdDeviation="1.5" result="coloredBlur" />
          <feMerge>
            <feMergeNode in="coloredBlur" />
            <feMergeNode in="SourceGraphic" />
          </feMerge>
        </filter>
        <linearGradient id="harvisBodyGradient" x1="0%" y1="0%" x2="0%" y2="100%">
          <stop offset="0%" stopColor="#4FD1C5" />
          <stop offset="100%" stopColor="#319795" />
        </linearGradient>
        <linearGradient id="harvisScreenGradient" x1="0%" y1="0%" x2="0%" y2="100%">
          <stop offset="0%" stopColor="#1A365D" />
          <stop offset="100%" stopColor="#0D1B2A" />
        </linearGradient>
        <linearGradient id="harvisAngryGradient" x1="0%" y1="0%" x2="0%" y2="100%">
          <stop offset="0%" stopColor="#FC8181" />
          <stop offset="100%" stopColor="#E53E3E" />
        </linearGradient>
      </defs>

      <g style={{ transformOrigin: "20px 8px", transform: `rotate(${antennaWiggle}deg)` }}>
        <line x1="20" y1="8" x2="16" y2="0" stroke={isAngry ? "#E53E3E" : "#4FD1C5"} strokeWidth="2" strokeLinecap="round" />
        <circle cx="16" cy="2" r="3" fill={isAngry ? "#E53E3E" : "#4FD1C5"} filter="url(#harvisGlow)" />
      </g>

      <g style={{ transformOrigin: "40px 8px", transform: `rotate(${-antennaWiggle}deg)` }}>
        <line x1="40" y1="8" x2="44" y2="0" stroke={isAngry ? "#E53E3E" : "#4FD1C5"} strokeWidth="2" strokeLinecap="round" />
        <circle cx="44" cy="2" r="3" fill={isAngry ? "#E53E3E" : "#4FD1C5"} filter="url(#harvisGlow)" />
      </g>

      <rect x="12" y="8" width="36" height="30" rx="6" fill={isAngry ? "url(#harvisAngryGradient)" : "url(#harvisBodyGradient)"} />
      <rect x="16" y="12" width="28" height="22" rx="3" fill="url(#harvisScreenGradient)" />

      <g style={{ transform: `translateX(${eyeOffset}px)`, transition: "transform 0.3s ease" }}>
        {isAngry ? (
          <>
            <line x1="19" y1="15" x2="28" y2="18" stroke="#E53E3E" strokeWidth="2.5" strokeLinecap="round" />
            <line x1="41" y1="15" x2="32" y2="18" stroke="#E53E3E" strokeWidth="2.5" strokeLinecap="round" />
            <ellipse cx="24" cy="22" rx="4" ry="2" fill="#E53E3E" />
            <ellipse cx="24" cy="22" rx="2" ry="1" fill="#FED7D7" />
            <ellipse cx="36" cy="22" rx="4" ry="2" fill="#E53E3E" />
            <ellipse cx="36" cy="22" rx="2" ry="1" fill="#FED7D7" />
          </>
        ) : isStartled ? (
          <>
            <circle cx="24" cy="20" r="5" fill="#4FD1C5" filter="url(#harvisGlow)" />
            <circle cx="24" cy="20" r="2.5" fill="#E6FFFA" />
            <circle cx="24" cy="19" r="1" fill="#ffffff" />
            <circle cx="36" cy="20" r="5" fill="#4FD1C5" filter="url(#harvisGlow)" />
            <circle cx="36" cy="20" r="2.5" fill="#E6FFFA" />
            <circle cx="36" cy="19" r="1" fill="#ffffff" />
          </>
        ) : isSmiling ? (
          <>
            <path d="M21 21 Q24 17 27 21" stroke="#4FD1C5" strokeWidth="2.5" strokeLinecap="round" fill="none" filter="url(#harvisGlow)" />
            <path d="M33 21 Q36 17 39 21" stroke="#4FD1C5" strokeWidth="2.5" strokeLinecap="round" fill="none" filter="url(#harvisGlow)" />
          </>
        ) : (
          <>
            <ellipse cx="24" cy="20" rx="3" ry="4" fill="#4FD1C5" filter="url(#harvisGlow)" />
            <ellipse cx="24" cy="20" rx="1.5" ry="2" fill="#E6FFFA" />
            <ellipse cx="36" cy="20" rx="3" ry="4" fill="#4FD1C5" filter="url(#harvisGlow)" />
            <ellipse cx="36" cy="20" rx="1.5" ry="2" fill="#E6FFFA" />
          </>
        )}
      </g>

      {isAngry ? (
        <path d="M24 30 Q30 26 36 30" stroke="#E53E3E" strokeWidth="2" strokeLinecap="round" fill="none" />
      ) : (isSmiling && !isStartled) && (
        <path d="M24 28 Q30 33 36 28" stroke="#4FD1C5" strokeWidth="2" strokeLinecap="round" fill="none" filter="url(#harvisGlow)" />
      )}

      <rect x="14" y="38" width="10" height="28" rx="3" fill={isAngry ? "url(#harvisAngryGradient)" : "url(#harvisBodyGradient)"} />
      <rect x="36" y="38" width="10" height="28" rx="3" fill={isAngry ? "url(#harvisAngryGradient)" : "url(#harvisBodyGradient)"} />
      <rect x="14" y="48" width="32" height="8" rx="2" fill={isAngry ? "url(#harvisAngryGradient)" : "url(#harvisBodyGradient)"} />

      <rect x="4" y="42" width="6" height="14" rx="3" fill={isAngry ? "#E53E3E" : "#4FD1C5"} />

      <g style={{ transformOrigin: "53px 42px", transform: `rotate(${armRotation}deg)`, transition: currentState === "wave" ? "none" : "transform 0.3s ease" }}>
        <rect x="50" y="42" width="6" height="14" rx="3" fill={isAngry ? "#E53E3E" : "#4FD1C5"} />
      </g>
    </svg>
  )
}
